### PR TITLE
Fix: Core API tests

### PR DESCRIPTION
**Pull request by fmitchell-r7**
This fixes up the Core API so all its tests pass. The code has been updated so the output for `/v1/health` and `/v1/status` doesn't change.

### CODE REVIEW

**Comment by jmanero-r7** [comment]
Is anything actually relying on these interfaces? These changes remove a lot of important debugging visibility

**Comment by fmitchell-r7** [comment]
@jmanero-r7 We can add more data to the existing APIs. I just don't want to remove anything that's already there without going to `/v2`. Putting `indices` and `sources` in the `/v1/status` API makes sense. Anything additional you want in `/v1/health`?

**Comment by fmitchell-r7** [comment]
We could also just do net new `/v2/health` and `/v2/status` APIs with all the extra debugging information in them.

**Comment by jmanero-r7** [comment]
🚢  it

**Pull request merged**
