### PR TITLE
Update source/common for Consul

### PR DESCRIPTION
**Pull request by jmanero-r7**
* Refactors into a base class and a polling class
* Exports factory methods to bind parsers to source classes
* Implements and tests correct inheritance checking
* Centralizes tests of the Source state-machine

### CODE REVIEW

**Comment by fmitchell-r7** [comment]
👍 Nice job with the stubs for the tests. It makes the test readable. :shipit:

**Comment by jmanero-r7** [comment]
Thanks. Ok to merge, or do you need more time to review?

**Comment by dgreene-r7** [comment]
Yeah that's elegant as hell. Nice job. Just gotta fix the linting errors and it'll be good to go.

Also, can you rename the PR just for reference?

**Comment by jmanero-r7** [comment]
The lint failures are only in the metadata test module. They're fixed in another commit already

**Comment by dgreene-r7** [comment]
> The lint failures are only in the metadata test module. They're fixed in another commit already

Cool. My one suggestion would be to split the `Source` class and `Polling` class into separate modules but that's really minor.

**Pull request merged**
