### PR TITLE
Feature application server

### PR DESCRIPTION
**Pull request by fmitchell-r7**
This sets up a basic HTTP server for propsd. None of the underpinning storage or plugin layers are there yet. But logging works and the server responds to GET requests on the `/v1/health` endpoint.

Singleton global `Config` and `Log` objects are defined so they can be leveraged by plugins.

### CODE REVIEW

**Comment by athompson-r7** [comment]
Nice readme.

Do the logs automatically roll or is that another set of config?

**Comment by fmitchell-r7** [comment]
@athompson-r7 Winston does provide [file rotation based on size and max number of files](https://github.com/winstonjs/winston/blob/master/docs/transports.md#file-transport). We could add configuration options to support that. For now, I updated the README to indicate that propsd doesn't handle log file rotation.

**Comment by athompson-r7** [comment]
:+1:

**Comment by dgreene-r7** [comment]
Looks good. Might want to toss it in the `bin/` directory just for consistency.

Also despite the awful code smell, we really should have singleton instances of the logger and config and put them in the global namespace just for simplicity's sake.

**Pull request merged**
